name: Build and Push to Deploy Branch

on:
  push:
    branches:
      - master # Triggers when you make changes to master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: ⚙️ Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 📦 Install dependencies
      run: npm install

    - name: 🚀 Build Project
      run: npm run build

    - name: 🌿 Isolate Dist into Deploy Branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: deploy # The bot will create and update this branch automatically
        folder: dist # It will grab everything INSIDE dist and put it at the root of the deploy branch
